- hosts: all

  vars:
    certbot_certs: []
      # - email: m@rcelko.ch
      #   webroot: "/usr/share/nginx/html"
      #   domains:
      #     - rcelko.ch
    certbot_install_method: snap

  roles:
     - jnv.unattended-upgrades
     - geerlingguy.certbot
     - geerlingguy.nginx
     - geerlingguy.docker